name: Upload to Codecov with retries
description: |
  Uploads to codecov with multiple retries as a workaround 
  for these issues
    - https://github.com/codecov/codecov-action/issues/598
    - https://github.com/codecov/codecov-action/issues/837
runs:
  using: composite
  steps:
    - name: "Upload to Codecov (attempt #1)"
      id: codecov-upload-1
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        fail_ci_if_error: true
        verbose: true
    - name: "Upload to Codecov (attempt #2)"
      id: codecov-upload-2
      if: steps.codecov-upload-1.outcome == 'failure'
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        fail_ci_if_error: true
        verbose: true
    - name: "Upload to Codecov (attempt #3)"
      id: codecov-upload-3
      if: steps.codecov-upload-2.outcome == 'failure'
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        fail_ci_if_error: true
        verbose: true
