version: '3.8'
services:
  localstack:
    image: "localstack/localstack:latest"
    environment:
      - "SERVICES=cloudwatch,kinesis,dynamodb,sts"
      - "KINESIS_LATENCY=0"
      - "LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}"
    healthcheck:
      test: "awslocal cloudwatch list-metrics && awslocal sts get-caller-identity"
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - "4566:4566"
  localstack-init:
    image: "amazon/aws-cli:latest"
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - "AWS_ACCESS_KEY_ID=test"
      - "AWS_SECRET_ACCESS_KEY=test"
      - "AWS_DEFAULT_REGION=us-east-1"
    entrypoint:
      - "aws"
      - "--endpoint-url=http://localstack:4566"
      - "kinesis"
      - "create-stream"
      - "--stream-name"
      - "test-kcl-service-stream"
      - "--shard-count"
      - "1"
  testKclService:
    image: "ghcr.io/etspaceman/kcl-http4s-test-server:${DOCKER_TAG_VERSION}"
    environment:
      - "LOG_LEVEL=TRACE"
      - "TEST_STREAM=test-kcl-service-stream"
      - "LOCALSTACK_HOST=localstack"
      - "DYNAMODB_IN_MEMORY=1"
      - "DYNAMODB_DELAY_TRANSIENT_STATUSES=0"
    healthcheck:
      test: "curl --fail http://localhost:8080/initialized || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
      localstack-init:
        condition: service_completed_successfully
  ready:
    image: "library/hello-world"
    depends_on:
      localstack:
        condition: service_healthy
      testKclService:
        condition: service_healthy
networks:
  default:
