version: '3.8'
services:
  localstack:
    image: "localstack/localstack:2.2.0"
    environment:
      - "SERVICES=cloudwatch,kinesis,dynamodb,sts"
      - "KINESIS_LATENCY=0"
      - "KINESIS_INITIALIZE_STREAMS=test-kcl-service-stream:1"
    healthcheck:
      test: "awslocal cloudwatch list-metrics && awslocal sts get-caller-identity"
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - "4566:4566"
  testKclService:
    image: "ghcr.io/etspaceman/integration-tests:${DOCKER_TAG_VERSION}"
    environment:
      - "LOG_LEVEL=TRACE"
      - "TEST_STREAM=test-kcl-service-stream"
      - "LOCALSTACK_HOST=localstack"
      - "DYNAMODB_IN_MEMORY=1"
      - "DYNAMODB_DELAY_TRANSIENT_STATUSES=0"
    healthcheck:
      test: "curl --fail http://localhost:8080/initialized || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
  ready:
    image: "library/hello-world"
    depends_on:
      localstack:
        condition: service_healthy
      testKclService:
        condition: service_healthy
networks:
  default:
