version: '2.4'
services:
  localstack:
    image: "localstack/localstack:latest"
    environment:
      - "SERVICES=cloudwatch,kinesis,dynamodb"
      - "KINESIS_LATENCY=0"
    healthcheck:
      test: "awslocal cloudwatch list-metrics"
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - "4566:4566"
  ready:
    image: "library/hello-world"
    depends_on:
      localstack:
        condition: service_healthy
networks:
  default:
    external:
      name: ${DOCKER_NET_NAME}
